# Generated by Django 3.1.1 on 2020-09-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20200925_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
